//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HocCatToc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hoccattocEntities : DbContext
    {
        public hoccattocEntities()
            : base("name=hoccattocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer_code> customer_code { get; set; }
        public virtual DbSet<video> videos { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<cat> cats { get; set; }
    }
}
