//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HocCatToc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class link
    {
        public int id { get; set; }
        public string youtube { get; set; }
        public string zalo { get; set; }
        public string fanpage { get; set; }
        public string facebook { get; set; }
    }
}
