//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HocCatToc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class video_group
    {
        public long id { get; set; }
        public Nullable<long> video_id { get; set; }
        public Nullable<int> group_id { get; set; }
    }
}
